<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>
    <NoWarn>$(NoWarn);NU1507</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Blazored.LocalStorage" Version="4.5.0" />
    <PackageVersion Include="CsvHelper" Version="33.1.0" />
    <PackageVersion Include="Fluxor" Version="6.1.0" />
    <PackageVersion Include="Fluxor.Blazor.Web" Version="6.1.0" />
    <PackageVersion Include="Fluxor.Blazor.Web.ReduxDevTools" Version="6.1.0" />
    <PackageVersion Include="KristofferStrube.Blazor.FileSystemAccess" Version="4.0.0" />
    <PackageVersion Include="Microsoft.AspNetCore.Components.WebAssembly" Version="10.0.11" />
    <PackageVersion Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="10.0.11" />
    <PackageVersion Include="Microsoft.AspNetCore.Components.WebView.Wpf" Version="10.0.100" />
    <PackageVersion Include="Microsoft.Extensions.Localization" Version="10.0.11" />
    <PackageVersion Include="Microsoft.FluentUI.AspNetCore.Components" Version="4.14.4" />
    <PackageVersion Include="Microsoft.FluentUI.AspNetCore.Components.Icons" Version="4.14.4" />
    <PackageVersion Include="PublishSPAforGitHubPages.Build" Version="3.0.0" />
  </ItemGroup>
</Project>